In [3]:
import sympy as sy
import numpy as np

FIRST METHOD

gradient 3x+4y=5
4y= 5-3x
y= 5/4 - 3/4x

In [35]:
x = np.linspace(0,20)
y = 5/4-3/4*x
#y = 3*x+4*y-5

np.gradient(y,x)


array([-0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75])

In [36]:
np.diff(y)/np.diff(x)

array([-0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75, -0.75,
       -0.75, -0.75, -0.75, -0.75])

SECOND METHOD

In [37]:
def f(x,y):
    return 3*x+4*y-5

In [41]:
x1 = np.linspace(0,20)
y1 = np.linspace(0,20)

z = np.array([[f(i,j)for i in x1]for j in y1])

In [42]:
dx, dy = np.gradient(z)

In [43]:
dx

array([[1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       ...,
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306],
       [1.63265306, 1.63265306, 1.63265306, ..., 1.63265306, 1.63265306,
        1.63265306]])

In [44]:
dy

array([[1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898],
       [1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898],
       [1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898],
       ...,
       [1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898],
       [1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898],
       [1.2244898, 1.2244898, 1.2244898, ..., 1.2244898, 1.2244898,
        1.2244898]])