In [1]:
import numpy as np

In [2]:
A = np.array([[1,-1],[6,4]])

In [3]:
eig_val, vec_eig=np.linalg.eig(A)

In [4]:
eig_val

array([2.5+1.93649167j, 2.5-1.93649167j])

In [5]:
vec_eig

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [7]:
from numpy import diag
from numpy.linalg import eig,inv

In [8]:
B=vec_eig.dot(diag(eig_val)).dot(inv(vec_eig))
B

array([[ 1.+1.40042907e-16j, -1.-1.64348860e-17j],
       [ 6.+2.45405006e-16j,  4.+1.39206967e-17j]])