In [1]:
import numpy as np


TENSOR

In [20]:
tensor = [[[23,50],[7,12]],
        [[57,67],[99,43]],
        [[75,21],[57,12]],
        [[87,26],[18,84]]]
tensor = np.array(tensor)   
tensor        

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [15]:
tensor.shape

(4, 2, 2)

MATRIX

In [25]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])
B = np.array([[17],
              [22],
              [19]])
print(A*B)                           

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


In [29]:
A = np.array([[23,50,19],
              [7,12,109],
              [57,67,98]])
A_transpose =  A.transpose()
A_determinan = np.linalg.det(A)
A_invers = np.linalg.inv(A)
print(A_transpose)
print(A_determinan)
print(A_invers)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]
131344.0000000002
[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
